token: <Discord Token>
spring:
  datasource:
    url: jdbc:postgresql://localhost/blubbspinat
    username: <username>
    password: <password>
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true